const { DataTypes } = require('sequelize');
const sequelize = require('../config/db'); 

const Post = sequelize.define('Post', {
    // Sequelize automatically adds an 'id' column as the Primary Key (PK) by default.
    // If you haven't explicitly set it to UUID, it will default to INTEGER/UUID depending on the dialect.
    // Assuming your default PK is UUID, we define the other fields:
    
    // We can explicitly define the PK to ensure consistency, often as UUID in microservices
    // Since your Identity Service uses integers, we'll keep this simple for now and focus on the FK.
    
    content: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    
    mediaUrl: {
        type: DataTypes.STRING,
        allowNull: true, // Optional
    },
    
    // ----------------------------------------------------------------
    // CRITICAL FIX: The userId must match the type generated by Identity Service (Integer)
    // ----------------------------------------------------------------
    userId: {
        type: DataTypes.INTEGER, // MUST MATCH THE INTEGER TYPE FROM IDENTITY SERVICE (e.g., '6')
        allowNull: false,
        // While not strictly enforced in a microservice (no direct FK constraint), 
        // the type must be INTEGER to accept the incoming data.
    },
    
    // Sequelize will automatically add createdAt and updatedAt if timestamps: true is set below
}, {
    timestamps: true,
    tableName: 'posts',
    // You might also want to set your Post ID (PK) type here if you were forcing UUID:
    // modelName: 'Post',
});

module.exports = Post;